# Generated by Django 6.0.1 on 2026-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('officeName', models.CharField(max_length=200)),
                ('officeCode', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
    ]
