# Generated by Django 6.0.1 on 2026-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=255)),
                ('officeCode', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
