# Generated by Django 6.0.1 on 2026-02-03 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0002_qprrecord_delete_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qprrecord',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='qprrecord',
            name='details',
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qprrecord',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='Section1FilesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.IntegerField(blank=True, null=True)),
                ('hindi_files', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section1', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section2MeetingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings_count', models.IntegerField(blank=True, null=True)),
                ('hindi_minutes', models.IntegerField(blank=True, null=True)),
                ('total_papers', models.IntegerField(blank=True, null=True)),
                ('hindi_papers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section2', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section3OfficialLanguagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_documents', models.IntegerField(blank=True, null=True)),
                ('bilingual_documents', models.IntegerField(blank=True, null=True)),
                ('english_only_documents', models.IntegerField(blank=True, null=True)),
                ('hindi_only_documents', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section3', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section4HindiLettersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_letters', models.IntegerField(blank=True, null=True)),
                ('no_reply_letters', models.IntegerField(blank=True, null=True)),
                ('replied_hindi_letters', models.IntegerField(blank=True, null=True)),
                ('replied_english_letters', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section4', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section5EnglishRepliedHindiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_a_english_letters', models.IntegerField(blank=True, null=True)),
                ('region_a_replied_hindi', models.IntegerField(blank=True, null=True)),
                ('region_a_replied_english', models.IntegerField(blank=True, null=True)),
                ('region_a_no_reply', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section5', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section6IssuedLettersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_a_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_a_english_only', models.IntegerField(blank=True, null=True)),
                ('region_a_total', models.IntegerField(blank=True, null=True)),
                ('region_b_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_b_english_only', models.IntegerField(blank=True, null=True)),
                ('region_b_total', models.IntegerField(blank=True, null=True)),
                ('region_c_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_c_english_only', models.IntegerField(blank=True, null=True)),
                ('region_c_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section6', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section7OtherLettersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_a_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_a_english_only', models.IntegerField(blank=True, null=True)),
                ('region_a_total', models.IntegerField(blank=True, null=True)),
                ('region_b_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_b_english_only', models.IntegerField(blank=True, null=True)),
                ('region_b_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section7', to='qpr_app.qprrecord')),
            ],
        ),
    ]
