# Generated by Django 6.0.1 on 2026-02-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0003_alter_qprrecord_options_remove_qprrecord_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section10HindiAdvisoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section10', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section11SpecificAchievementsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovative_work', models.TextField(blank=True, null=True)),
                ('special_events', models.TextField(blank=True, null=True)),
                ('hindi_medium_works', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section11', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section7NotingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi_pages', models.IntegerField(blank=True, null=True)),
                ('english_pages', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('eoffice_notings', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section7', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section8WorkshopsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_day_workshops', models.IntegerField(blank=True, null=True)),
                ('officers_trained', models.IntegerField(blank=True, null=True)),
                ('employees_trained', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section8', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section9ImplementationCommitteeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('sub_committees_count', models.IntegerField(blank=True, null=True)),
                ('meetings_organized', models.IntegerField(blank=True, null=True)),
                ('agenda_hindi', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section9', to='qpr_app.qprrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='Section7OtherLettersData',
        ),
    ]
