# Generated by Django 6.0.1 on 2026-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0006_qprrecord_is_submitted_managerrequest_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='office_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
