# Generated by Django 6.0.1 on 2026-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0007_userprofile_office_code_userprofile_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hod_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
