# Generated by Django 6.0.1 on 2026-02-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpr_app', '0008_alter_userprofile_hod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprrecord',
            name='year',
            field=models.CharField(blank=True, default='2025-2026', max_length=20, null=True),
        ),
    ]
