# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_employee_super_annuation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parangat',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Did not Appear', 'Did not Appear')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prabodh',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Did not Appear', 'Did not Appear')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pragya',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Did not Appear', 'Did not Appear')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='praveen',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Did not Appear', 'Did not Appear')], default='', max_length=20),
        ),
    ]
