# Generated by Django 6.0.1 on 2026-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_customuser_role_editrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('used', 'Used')], default='pending', max_length=20),
        ),
    ]
