# Generated by Django 6.0.1 on 2026-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_qprparttwo_is_submitted_qprparttwo_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='parangat',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='prabodh',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pragya',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='praveen',
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_exam',
            field=models.CharField(blank=True, choices=[('Prabodh', 'Prabodh'), ('Praveen', 'Praveen'), ('Pragya', 'Pragya'), ('Parangat', 'Parangat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Scientist-F', 'Scientist-F'), ('Scientist-G', 'Scientist-G'), ('Scientist-E', 'Scientist-E'), ('Scientist-D', 'Scientist-D'), ('Scientist-C', 'Scientist-C'), ('Scientist-B', 'Scientist-B'), ('Section Officer', 'Section Officer'), ('Senior Secretariate Assistant', 'Senior Secretariate Assistant'), ('Scientific/Technical Assistant-A', 'Scientific/Technical Assistant-A'), ('Scientific/Technical Assistant-B', 'Scientific/Technical Assistant-B'), ('Scientific Officer/Engineer-SB', 'Scientific Officer/Engineer-SB')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hindiproficiency',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
