# Generated by Django 6.0.1 on 2026-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_qprrecord_frequency_qprrecord_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprrecord',
            name='is_quarterly_frozen',
            field=models.BooleanField(default=False, help_text='Freeze quarterly report on quarter end (HOD can freeze only at quarter end)'),
        ),
    ]
