# Generated by Django 6.0.1 on 2026-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_userprofile_alternate_email_userprofile_ip_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
