# Generated by Django 6.0.1 on 2026-04-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_userprofile_profile_locked_and_more'),
        ('website', '0049_alter_customuser_email_hash'),
    ]

    operations = [
    ]
