# Generated by Django 6.0.1 on 2026-04-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_remove_userprofile_profile_locked_and_more'),
        ('website', '0051_userprofile_employee'),
    ]

    operations = [
    ]
