# Generated by Django 6.0.3 on 2026-04-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_editrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='requested_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
