# Generated by Django 6.0.1 on 2026-04-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_employee_stenographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20)),
                ('quarter', models.CharField(max_length=50)),
                ('section_2', models.IntegerField(blank=True, null=True)),
                ('section_3_text', models.TextField(blank=True, null=True)),
                ('section_4', models.IntegerField(blank=True, null=True)),
                ('section_5', models.IntegerField(blank=True, null=True)),
                ('section_6', models.IntegerField(blank=True, null=True)),
                ('section_7', models.IntegerField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_qprs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='ManagerQPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20)),
                ('quarter', models.CharField(max_length=50)),
                ('section_2', models.IntegerField(blank=True, null=True)),
                ('section_4', models.IntegerField(blank=True, null=True)),
                ('section_5', models.IntegerField(blank=True, null=True)),
                ('section_6', models.IntegerField(blank=True, null=True)),
                ('section_7', models.IntegerField(blank=True, null=True)),
                ('section_8_text', models.TextField(blank=True, null=True)),
                ('section_9_date', models.DateField(blank=True, null=True)),
                ('section_10_yesno', models.BooleanField(default=False)),
                ('section_11_text', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_qprs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quarter')},
            },
        ),
    ]
