# Generated by Django 6.0.1 on 2026-05-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_merge_20260509_1610'),
        ('website', '0065_delete_typingusagereport'),
    ]

    operations = [
    ]
