# Generated by Codex on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_merge_20260511_0130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminqpr',
            unique_together={('user', 'quarter', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='managerqpr',
            unique_together={('user', 'quarter', 'financial_year')},
        ),
    ]
