# Generated by Django 6.0.1 on 2026-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_employeemaster_is_active_employeemaster_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminqpr',
            name='a_s1_hindi_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s1_total_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s3_bilingual_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s3_english_only_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s3_hindi_only_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s3_total_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
