# Generated by Django 6.0.1 on 2026-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_adminqpr_a_s1_hindi_files_adminqpr_a_s1_total_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerqpr',
            name='s1_hindi_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s1_total_files',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
