# Generated by Django 6.0.1 on 2026-06-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_managerqpr_s1_hindi_files_managerqpr_s1_total_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminqpr',
            name='a_s1_hindi_files',
        ),
        migrations.RemoveField(
            model_name='adminqpr',
            name='a_s1_total_files',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s1_hindi_files',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s1_total_files',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s3_bilingual_documents',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s3_english_only_documents',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s3_hindi_only_documents',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='s3_total_documents',
        ),
    ]
