# Generated by Django 6.0.1 on 2026-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.IntegerField()),
                ('ename', models.CharField(max_length=255, verbose_name='Name in English')),
                ('hname', models.CharField(max_length=255, verbose_name='Name in Hindi')),
                ('desig', models.CharField(max_length=100, verbose_name='Designation in English')),
                ('gazet', models.TextField()),
                ('prabodh', models.TextField()),
                ('praveen', models.TextField()),
                ('pragya', models.TextField()),
                ('parangat', models.TextField()),
                ('typing', models.TextField()),
                ('hindiproficiency', models.TextField()),
                ('lastupdate', models.DateTimeField(verbose_name='Last Updated on')),
            ],
        ),
    ]
