# Generated by Django 6.0.1 on 2026-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_employee_superannuationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lastupdate',
            field=models.DateField(auto_now=True, verbose_name='Last Updated on'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='superannuationDate',
            field=models.DateField(blank=True, null=True, verbose_name='Superannuation Date'),
        ),
    ]
