# Generated by Django 6.0 on 2026-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_employee_designation_alter_employee_empcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gazet',
            field=models.CharField(choices=[('Gazetted', 'Gazetted'), ('Non-Gazetted', 'Non-Gazetted')], max_length=50),
        ),
    ]
