# Generated by Django 6.0 on 2026-01-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
    ]
