# Generated by Django 6.0 on 2026-01-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_employee_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='super_annuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Superannuation Date'),
        ),
    ]
