# Generated by Django 6.0.1 on 2026-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_employee_parangat_alter_employee_prabodh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='parangat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prabodh',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pragya',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='praveen',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
