# Generated by Django 6.0 on 2026-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_employee_hindiproficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hindiproficiency',
            field=models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Basic', 'Basic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='typing',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Both', 'Both')], max_length=30),
        ),
    ]
