# Generated by Django 6.0.1 on 2026-02-07 07:15

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0011_alter_employee_hindiproficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email_hash', models.CharField(max_length=64)),
                ('encrypted_email_data', models.BinaryField()),
                ('employee_snapshot', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
