# Generated by Django 6.0.1 on 2026-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_archiveduser_alter_employee_ename_customuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='super_annuation_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='encrypted_super_annuation_date',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
