# Generated by Django 6.0.1 on 2026-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_managerrequest_qprrecord_section10hindiadvisorydata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin'), ('backup_user', 'Backup User'), ('hod', 'HOD')], default='user', max_length=20),
        ),
    ]
