# Generated by Django 6.0.1 on 2026-02-21 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_editrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingUsageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(blank=True, null=True)),
                ('hindi_words', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='typing_usage_report', to='website.qprrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
