# Generated by Django 6.0.1 on 2026-03-01 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(max_length=50, unique=True)),
                ('office_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['office_code'],
            },
        ),
    ]
