# Generated by Django 6.0.1 on 2026-03-01 14:44

from django.db import migrations


def assign_default_roles(apps, schema_editor):
    """Assign default 'user' role to all existing users and sync with profiles"""
    from django.contrib.auth import get_user_model
    User = apps.get_model('website', 'CustomUser')
    UserProfile = apps.get_model('website', 'UserProfile')
    Role = apps.get_model('website', 'Role')
    
    # Get or create the roles
    user_role, _ = Role.objects.get_or_create(name='user')
    admin_role, _ = Role.objects.get_or_create(name='admin')
    
    # Assign 'user' role to all regular users
    for user in User.objects.filter(is_superuser=False, is_staff=False):
        if not user.roles.exists():
            user.roles.add(user_role)
        # Also sync with profile if it exists
        try:
            profile = UserProfile.objects.get(user=user)
            if not profile.roles.exists():
                profile.roles.add(user_role)
        except UserProfile.DoesNotExist:
            pass
    
    # Assign 'admin' role to all superusers
    for user in User.objects.filter(is_superuser=True):
        if not user.roles.filter(name='admin').exists():
            user.roles.add(admin_role)
        # Also sync with profile if it exists
        try:
            profile = UserProfile.objects.get(user=user)
            if not profile.roles.filter(name='admin').exists():
                profile.roles.add(admin_role)
        except UserProfile.DoesNotExist:
            pass


def reverse_assign_roles(apps, schema_editor):
    """Reverse: clear all role assignments (except those needed)"""
    User = apps.get_model('website', 'CustomUser')
    # Note: We'll keep the roles as they are for safety
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_populate_roles'),
    ]

    operations = [
        migrations.RunPython(assign_default_roles, reverse_assign_roles),
    ]
