# Generated by Django 6.0.1 on 2026-03-01 15:39

from django.db import migrations


def fix_admin_roles(apps, schema_editor):
    """Fix admin roles for existing superusers and their profiles"""
    User = apps.get_model('website', 'CustomUser')
    UserProfile = apps.get_model('website', 'UserProfile')
    Role = apps.get_model('website', 'Role')
    
    # Get or create the 'admin' role
    try:
        admin_role = Role.objects.get(name='admin')
    except Role.DoesNotExist:
        admin_role = Role.objects.create(name='admin', description='Admin')
    
    # Fix superusers - assign admin role
    for user in User.objects.filter(is_superuser=True):
        if not user.roles.filter(name='admin').exists():
            user.roles.add(admin_role)
        
        # Also fix their profiles
        try:
            profile = UserProfile.objects.get(user=user)
            if not profile.roles.filter(name='admin').exists():
                profile.roles.add(admin_role)
        except UserProfile.DoesNotExist:
            # Create profile if missing
            profile = UserProfile.objects.create(
                user=user,
                employee_code=user.username
            )
            profile.roles.add(admin_role)


def reverse_fix_admin_roles(apps, schema_editor):
    """Reverse: Keep roles as-is for safety"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_migrate_existing_roles'),
    ]

    operations = [
        migrations.RunPython(fix_admin_roles, reverse_fix_admin_roles),
    ]
