# Generated by Django 6.0.1 on 2026-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_fix_existing_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprrecord',
            name='cert_edit_count',
            field=models.IntegerField(default=0, help_text='Track certificate edits (max 2)'),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='cert_office_code',
            field=models.CharField(blank=True, help_text='Override office code for certificate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='cert_quarter',
            field=models.CharField(blank=True, help_text='Override quarter for certificate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='cert_year',
            field=models.CharField(blank=True, help_text='Override year for certificate', max_length=20, null=True),
        ),
    ]
