# Generated by Django 6.0.1 on 2026-03-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_qprrecord_cert_edit_count_qprrecord_cert_office_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typingusagereport',
            options={},
        ),
        migrations.CreateModel(
            name='CertificateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(max_length=50)),
                ('financial_year', models.CharField(max_length=20)),
                ('quarter_ending', models.CharField(max_length=50)),
                ('chairperson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chairperson_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_filled', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_uploaded', models.BooleanField(default=False)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_data', to='website.qprrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
