# Generated by Django 6.0.1 on 2026-03-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_typingusagereport_options_certificatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedata',
            name='chairperson_designation',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='chairperson_name',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='date_filled',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='office_code',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='phone_fax',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='place',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='signature_file',
        ),
        migrations.RemoveField(
            model_name='certificatedata',
            name='signature_uploaded',
        ),
    ]
