# Generated by Django 6.0.1 on 2026-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_certificatedata_chairperson_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprrecord',
            name='is_editing_allowed',
            field=models.BooleanField(default=False, help_text='Allow editing of submitted form after unlock'),
        ),
    ]
