# Generated by Django 6.0.1 on 2026-03-04 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_qprrecord_is_editing_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPRPartTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g., 2023-24', max_length=20)),
                ('is_notified_rule_10_4', models.BooleanField(default=False, verbose_name='Notified under Rule 10(4)')),
                ('total_sub_offices', models.PositiveIntegerField(default=0)),
                ('notified_sub_offices', models.PositiveIntegerField(default=0)),
                ('computer_training_total_staff', models.PositiveIntegerField(default=0)),
                ('computer_training_trained', models.PositiveIntegerField(default=0)),
                ('computer_training_working', models.PositiveIntegerField(default=0)),
                ('total_computers', models.PositiveIntegerField(default=0)),
                ('hindi_enabled_computers', models.PositiveIntegerField(default=0)),
                ('officials_issued_rule_8_4_orders', models.PositiveIntegerField(default=0)),
                ('training_total_duration_hours', models.PositiveIntegerField(default=0)),
                ('training_imparted_hindi', models.PositiveIntegerField(default=0)),
                ('training_imparted_english', models.PositiveIntegerField(default=0)),
                ('training_imparted_mixed', models.PositiveIntegerField(default=0)),
                ('sec8_total_sections', models.PositiveIntegerField(default=0)),
                ('sec8_inspected_sections', models.PositiveIntegerField(default=0)),
                ('sec8_total_sub_offices', models.PositiveIntegerField(default=0)),
                ('sec8_inspected_sub_offices', models.PositiveIntegerField(default=0)),
                ('magazines_total', models.PositiveIntegerField(default=0)),
                ('magazines_hindi', models.PositiveIntegerField(default=0)),
                ('magazines_english', models.PositiveIntegerField(default=0)),
                ('expenditure_total_books', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expenditure_hindi_books', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hindi_event_start_date', models.DateField(blank=True, null=True)),
                ('hindi_event_end_date', models.DateField(blank=True, null=True)),
                ('seminar_date', models.DateField(blank=True, null=True)),
                ('seminar_subject', models.CharField(blank=True, max_length=255)),
                ('other_activities_date', models.DateField(blank=True, null=True)),
                ('other_activities_subject', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficersWorkInHindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ds_and_above', 'Deputy Secretary/Equivalent and above'), ('below_ds', 'Below the level of Deputy Secretary/Equivalent')], max_length=50)),
                ('total_officers', models.PositiveIntegerField(default=0)),
                ('knowledge_of_hindi', models.PositiveIntegerField(default=0)),
                ('not_doing', models.PositiveIntegerField(default=0)),
                ('doing_upto_25', models.PositiveIntegerField(default=0)),
                ('doing_26_to_50', models.PositiveIntegerField(default=0)),
                ('doing_51_to_75', models.PositiveIntegerField(default=0)),
                ('doing_more_76', models.PositiveIntegerField(default=0)),
                ('doing_cent_percent', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers_work', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='HindiPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('sanctioned', models.PositiveIntegerField(default=0)),
                ('vacant', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindi_posts', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='CodeManualStandardForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('acts_rules', 'Acts/Rules/Official codes/Manuals/Procedural literature etc.'), ('standard_forms', 'Standard Forms')], max_length=50)),
                ('total_no', models.PositiveIntegerField(default=0)),
                ('bilingual_no', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_manuals', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffHindiKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('proficient', 'Proficient'), ('working_knowledge', 'Working Knowledge'), ('being_trained', 'Being trained in Hindi'), ('yet_to_be_trained', 'Yet to be trained in Hindi')], max_length=50)),
                ('officers_count', models.PositiveIntegerField(default=0)),
                ('employees_count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_knowledge', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('engaged', 'Engaged in Translation Work'), ('trained', 'Got training in Translation'), ('yet_to_be_trained', 'Yet to be trained')], max_length=50)),
                ('officers_count', models.PositiveIntegerField(default=0)),
                ('employees_count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_knowledge', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='TypingStenographyKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('stenographer', 'Stenographer'), ('typist_clerk', 'Typists/Clerks/Assistant Section Officer'), ('tax_postal', 'Tax/Postal Asstt. etc.')], max_length=50)),
                ('total_no', models.PositiveIntegerField(default=0)),
                ('trained_in_hindi', models.PositiveIntegerField(default=0)),
                ('work_in_hindi', models.PositiveIntegerField(default=0)),
                ('yet_to_be_trained', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_knowledge', to='website.qprparttwo')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Address of Website')),
                ('status', models.CharField(choices=[('english_only', 'Only in English'), ('partially_bilingual', 'Partially Bilingual'), ('fully_bilingual', 'Fully Bilingual')], max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='website.qprparttwo')),
            ],
        ),
    ]
