# Generated by Django 6.0.1 on 2026-03-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_qprparttwo_officersworkinhindi_hindipost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprparttwo',
            name='qpr_record',
            field=models.OneToOneField(blank=True, help_text='Optional link to the main QPRRecord when created from manager UI', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part2', to='website.qprrecord'),
        ),
    ]
