# Generated by Django 6.0.1 on 2026-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_qprparttwo_qpr_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprparttwo',
            name='chairperson_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='chairperson_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='chairperson_fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='chairperson_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='chairperson_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
