# Generated by Django 6.0.1 on 2026-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_qprparttwo_chairperson_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhindiknowledge',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translationknowledge',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
