# Generated by Django 6.0.1 on 2026-03-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_staffhindiknowledge_total_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprparttwo',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_part2', to=settings.AUTH_USER_MODEL),
        ),
    ]
