# Generated by Django 6.0.1 on 2026-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_remove_employee_parangat_remove_employee_prabodh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='olic_affiliate',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Member Secretary', 'Member Secretary'), ('Member', 'Member')], max_length=50, null=True),
        ),
    ]
