# Generated by Django 6.0.1 on 2026-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_userprofile_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_phone',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
