# Generated by Django 6.0.1 on 2026-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_employee_olic_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('Scientist-G', 'Scientist-G'), ('Scientist-F', 'Scientist-F'), ('Scientist-E', 'Scientist-E'), ('Scientist-D', 'Scientist-D'), ('Scientist-C', 'Scientist-C'), ('Scientist-B', 'Scientist-B'), ('Section Officer', 'Section Officer'), ('Senior Secretariate Assistant', 'Senior Secretariate Assistant'), ('Scientific/Technical Assistant-A', 'Scientific/Technical Assistant-A'), ('Scientific/Technical Assistant-B', 'Scientific/Technical Assistant-B'), ('Scientific Officer/Engineer-SB', 'Scientific Officer/Engineer-SB')], max_length=100, null=True),
        ),
    ]
