# Generated by Django 6.0.1 on 2026-03-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='highest_exam',
            field=models.CharField(blank=True, choices=[('Prabodh', 'Prabodh'), ('Praveen', 'Praveen'), ('Pragya', 'Pragya'), ('Parangat', 'Parangat')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='olic_affiliate',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Member Secretary', 'Member Secretary'), ('Member', 'Member'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True),
        ),
    ]
