# Generated by Django 6.0.1 on 2026-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_employee_highest_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qprrecord',
            name='region',
            field=models.CharField(blank=True, choices=[('Region A', "भाषा क्षेत्र 'क' / Region A"), ('Region B', "भाषा क्षेत्र 'ख' / Region B"), ('Region C', "भाषा क्षेत्र 'ग' / Region C")], max_length=50, null=True),
        ),
    ]
