# Generated by Django 6.0.1 on 2026-03-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_userprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprrecord',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='quarterly', max_length=20),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qprrecord',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
