# Generated by Django 6.0.1 on 2026-03-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_financialyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
