# Generated by Django 6.0.1 on 2026-03-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_qprrecord_region'),
        ('website', '0045_userprofile_language_region'),
    ]

    operations = [
    ]
