# Generated by Django 6.0.3 on 2026-03-31 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_merge_20260327_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Optional alternate email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_number',
            field=models.CharField(blank=True, help_text='Auto-filled from employee database', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_state',
            field=models.CharField(blank=True, help_text='Auto-filled from employee database', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_profile_changes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='website.userprofile')),
            ],
        ),
    ]
