# Generated by Django 6.0.3 on 2026-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_userprofile_alternate_email_userprofile_ip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending HOD Approval'), ('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
