# Generated by Django 6.0.1 on 2026-04-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_userprofile_alternate_email'),
        ('website', '0048_userprofile_profile_locked_and_more'),
    ]

    operations = [
    ]
