# Generated by Django 6.0.1 on 2026-04-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_merge_20260405_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_locked',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending HOD Approval'), ('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
