# Generated by Django 6.0.3 on 2026-04-14 09:52

from django.db import migrations, models


def rename_used_to_temp_use(apps, schema_editor):
    EditRequest = apps.get_model('website', 'EditRequest')
    EditRequest.objects.filter(status='used').update(status='temp use')


def rename_temp_use_to_used(apps, schema_editor):
    EditRequest = apps.get_model('website', 'EditRequest')
    EditRequest.objects.filter(status='temp use').update(status='used')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_userprofile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('temp use', 'Temp Use')], default='pending', max_length=20),
        ),
        migrations.RunPython(rename_used_to_temp_use, rename_temp_use_to_used),
    ]
