# Generated by Django 6.0.3 on 2026-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_profilechangerequest_requested_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stenographer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
