# Generated by Django 6.0.1 on 2026-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_adminqpr_managerqpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminqpr',
            old_name='section_2',
            new_name='a_s2_hindi_minutes',
        ),
        migrations.RenameField(
            model_name='adminqpr',
            old_name='section_4',
            new_name='a_s2_hindi_papers',
        ),
        migrations.RenameField(
            model_name='adminqpr',
            old_name='section_5',
            new_name='a_s2_meetings_count',
        ),
        migrations.RenameField(
            model_name='adminqpr',
            old_name='section_6',
            new_name='a_s2_total_papers',
        ),
        migrations.RenameField(
            model_name='adminqpr',
            old_name='section_7',
            new_name='a_s3_bilingual_documents',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_9_date',
            new_name='s10_meeting_date',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_11_text',
            new_name='s11_hindi_medium_works',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_8_text',
            new_name='s11_innovative_work',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_2',
            new_name='s2_hindi_minutes',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_4',
            new_name='s2_hindi_papers',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_5',
            new_name='s2_meetings_count',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_6',
            new_name='s2_total_papers',
        ),
        migrations.RenameField(
            model_name='managerqpr',
            old_name='section_7',
            new_name='s4_no_reply_letters',
        ),
        migrations.RemoveField(
            model_name='adminqpr',
            name='section_3_text',
        ),
        migrations.RemoveField(
            model_name='managerqpr',
            name='section_10_yesno',
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s3_english_only_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s3_hindi_only_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s3_total_documents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s4_no_reply_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s4_replied_english_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s4_replied_hindi_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s4_total_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s5_region_a_english_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s5_region_a_no_reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s5_region_a_replied_english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s5_region_a_replied_hindi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_a_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_a_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_a_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_b_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_b_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_b_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_c_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_c_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s6_region_c_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s7_english_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s7_eoffice_notings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s7_hindi_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminqpr',
            name='a_s7_total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s11_special_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s4_replied_english_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s4_replied_hindi_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s4_total_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s5_region_a_english_letters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s5_region_a_no_reply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s5_region_a_replied_english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s5_region_a_replied_hindi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_a_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_a_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_a_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_b_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_b_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_b_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_c_english_only',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_c_hindi_bilingual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s6_region_c_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s7_english_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s7_eoffice_notings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s7_hindi_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s7_total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s8_employees_trained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s8_full_day_workshops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s8_officers_trained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s9_agenda_hindi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s9_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s9_meetings_organized',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerqpr',
            name='s9_sub_committees_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
