# Generated by Django 6.0.3 on 2026-05-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_userprofile_profile_locked_and_more'),
        ('website', '0056_rename_section_2_adminqpr_a_s2_hindi_minutes_and_more'),
    ]

    operations = [
    ]
