# Generated by Django 6.0.1 on 2026-04-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_merge_20260424_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPRFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qpr_finalizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finalized_at'],
                'unique_together': {('user', 'quarter', 'year')},
            },
        ),
    ]
