# Generated by Django 6.0.1 on 2026-04-26 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_qprfinalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprparttwo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='quarter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part2_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='qprparttwo',
            unique_together={('user', 'quarter', 'year')},
        ),
    ]
