# Generated by Django 6.0.1 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_rename_employees_count_staffhindiknowledge_employees_proficient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hindipost',
            old_name='sanctioned',
            new_name='hq_sanctioned',
        ),
        migrations.RenameField(
            model_name='hindipost',
            old_name='vacant',
            new_name='hq_vacant',
        ),
        migrations.AddField(
            model_name='hindipost',
            name='sub_sanctioned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hindipost',
            name='sub_vacant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hindipost',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
