# Generated by Django 6.0.3 on 2026-05-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_merge_20260503_1251'),
        ('website', '0061_rename_sanctioned_hindipost_hq_sanctioned_and_more'),
    ]

    operations = [
    ]
