# Generated by Django 6.0.1 on 2026-04-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_merge_20260422_2355'),
        ('website', '0061_rename_sanctioned_hindipost_hq_sanctioned_and_more'),
    ]

    operations = [
    ]
