# Generated by Codex on 2026-05-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_monthlyfill_monthlysnapshot_quarterlyfill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='has_language_option',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ManagerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('financial_year', models.CharField(max_length=20)),
                ('office_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_submitted', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quarter', 'year')},
            },
        ),
    ]
