# Generated by Django 6.0.1 on 2026-05-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_merge_20260503_1251'),
        ('website', '0062_merge_20260430_1145'),
    ]

    operations = [
    ]
