# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_managercertificate_websitedetail_language_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercertificate',
            name='certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='chairperson_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='chairperson_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='phone_fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='managercertificate',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managercertificate',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managercertificate',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
