# Generated by Django 6.0.1 on 2026-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_merge_20260505_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
