# Generated by Codex on 2026-05-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_managercertificate_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingUsageReport',
        ),
    ]
