# Generated by Django 6.0.1 on 2026-05-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_merge_20260509_1610'),
        ('website', '0062_monthlyfill_monthlysnapshot_quarterlyfill_and_more'),
        ('website', '0064_office_state'),
    ]

    operations = [
    ]
