# Generated by Django 6.0.1 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_manager_admin_qpr_unique_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
