# Generated by Django 6.0 on 2026-01-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='desig',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='gazet',
            field=models.CharField(max_length=50),
        ),
    ]
