# Generated by Django 6.0 on 2026-02-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_employee_parangat_alter_employee_prabodh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hindiproficiency',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Basic', 'Basic'), ('Not Applicable', 'Not Applicable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='parangat',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prabodh',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pragya',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='praveen',
            field=models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='typing',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Hindi & English', 'Hindi & English'), ('Not Applicable', 'Not Applicable')], max_length=30),
        ),
    ]
