# Generated by Django 6.0.1 on 2026-02-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('profile', 'Profile Update'), ('qpr', 'QPR Update'), ('both', 'Both Profile and QPR')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QPRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=255)),
                ('officeCode', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, default='2025-2026', max_length=20, null=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qpr_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Section10HindiAdvisoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section10', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section11SpecificAchievementsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovative_work', models.TextField(blank=True, null=True)),
                ('special_events', models.TextField(blank=True, null=True)),
                ('hindi_medium_works', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section11', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section1FilesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.IntegerField(blank=True, null=True)),
                ('hindi_files', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section1', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section2MeetingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetings_count', models.IntegerField(blank=True, null=True)),
                ('hindi_minutes', models.IntegerField(blank=True, null=True)),
                ('total_papers', models.IntegerField(blank=True, null=True)),
                ('hindi_papers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section2', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section3OfficialLanguagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_documents', models.IntegerField(blank=True, null=True)),
                ('bilingual_documents', models.IntegerField(blank=True, null=True)),
                ('english_only_documents', models.IntegerField(blank=True, null=True)),
                ('hindi_only_documents', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section3', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section4HindiLettersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_letters', models.IntegerField(blank=True, null=True)),
                ('no_reply_letters', models.IntegerField(blank=True, null=True)),
                ('replied_hindi_letters', models.IntegerField(blank=True, null=True)),
                ('replied_english_letters', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section4', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section5EnglishRepliedHindiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_a_english_letters', models.IntegerField(blank=True, null=True)),
                ('region_a_replied_hindi', models.IntegerField(blank=True, null=True)),
                ('region_a_replied_english', models.IntegerField(blank=True, null=True)),
                ('region_a_no_reply', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section5', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section6IssuedLettersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_a_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_a_english_only', models.IntegerField(blank=True, null=True)),
                ('region_a_total', models.IntegerField(blank=True, null=True)),
                ('region_b_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_b_english_only', models.IntegerField(blank=True, null=True)),
                ('region_b_total', models.IntegerField(blank=True, null=True)),
                ('region_c_hindi_bilingual', models.IntegerField(blank=True, null=True)),
                ('region_c_english_only', models.IntegerField(blank=True, null=True)),
                ('region_c_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section6', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section7NotingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi_pages', models.IntegerField(blank=True, null=True)),
                ('english_pages', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('eoffice_notings', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section7', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section8WorkshopsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_day_workshops', models.IntegerField(blank=True, null=True)),
                ('officers_trained', models.IntegerField(blank=True, null=True)),
                ('employees_trained', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section8', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Section9ImplementationCommitteeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('sub_committees_count', models.IntegerField(blank=True, null=True)),
                ('meetings_organized', models.IntegerField(blank=True, null=True)),
                ('agenda_hindi', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qpr_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section9', to='website.qprrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('hod', 'HOD'), ('admin', 'Admin/Manager')], default='user', max_length=10)),
                ('hod_name', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_code', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
