# Generated by Django 6.0.1 on 2026-03-01 14:43

from django.db import migrations


def populate_roles(apps, schema_editor):
    """Create the 5 standard roles"""
    Role = apps.get_model('website', 'Role')
    
    role_data = [
        ('user', 'User'),
        ('manager', 'Manager'),
        ('hod', 'HOD'),
        ('admin', 'Admin'),
        ('backup_user', 'Backup User'),
    ]
    
    for name, description in role_data:
        Role.objects.get_or_create(
            name=name,
            defaults={'description': description}
        )


def reverse_populate_roles(apps, schema_editor):
    """Delete all roles (reverse operation)"""
    Role = apps.get_model('website', 'Role')
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_roles, reverse_populate_roles),
    ]
