# Generated by Django 6.0.1 on 2026-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_qprparttwo_created_at_qprparttwo_quarter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffhindiknowledge',
            old_name='employees_count',
            new_name='employees_proficient',
        ),
        migrations.RenameField(
            model_name='staffhindiknowledge',
            old_name='officers_count',
            new_name='employees_total',
        ),
        migrations.AddField(
            model_name='qprparttwo',
            name='hindi_work_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='staffhindiknowledge',
            name='employees_working',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffhindiknowledge',
            name='officers_proficient',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffhindiknowledge',
            name='officers_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffhindiknowledge',
            name='officers_working',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffhindiknowledge',
            name='category',
            field=models.CharField(choices=[('total', 'Total'), ('secretarial', 'Secretarial'), ('knowledge', 'Knowledge of Hindi'), ('being_trained', 'Being trained'), ('yet_to_be_trained', 'Yet to be trained')], max_length=50),
        ),
    ]
