# Generated by Django 6.0.3 on 2026-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_employeemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='transferred_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
