# Generated by Django 6.0.1 on 2026-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_encrypted_email_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
