# Generated by Django 6.0.1 on 2026-01-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
