# Generated by Django 6.0.1 on 2026-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
