# Generated by Django 6.0.1 on 2026-02-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_is_archived_customuser_is_edit_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email_hash', models.CharField(max_length=64)),
                ('encrypted_email_data', models.BinaryField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin'), ('backup_user', 'Backup User')], default='user', max_length=20),
        ),
    ]
