# Generated by Django 6.0.1 on 2026-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_archiveduser_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.IntegerField(unique=True)),
                ('ename', models.CharField(max_length=255)),
                ('hname', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('gazet', models.CharField(choices=[('Gazetted', 'Gazetted'), ('Non-Gazetted', 'Non-Gazetted')], max_length=50)),
                ('prabodh', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20)),
                ('praveen', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20)),
                ('pragya', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20)),
                ('parangat', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Did not Appear', 'Did not Appear')], max_length=20)),
                ('typing', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Both', 'Both')], max_length=30)),
                ('hindiproficiency', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Basic', 'Basic')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('lastupdate', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
                ('super_annuation_date', models.DateField(blank=True, null=True, verbose_name='Superannuation Date')),
            ],
        ),
    ]
