# Generated by Django 6.0.1 on 2026-02-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AddField(
            model_name='archiveduser',
            name='employee_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='encrypted_ename',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
