# Generated by Django 6.0.1 on 2026-02-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_employee_ename_archiveduser_employee_snapshot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='encrypted_ename',
            new_name='ename',
        ),
    ]
