# Generated by Django 6.0.1 on 2026-02-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_encrypted_ename_employee_ename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(blank=True, null=True),
        ),
    ]
