# Generated by Django 6.0.1 on 2026-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_employee_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='encrypted_super_annuation_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
