# Generated by Django 6.0.1 on 2026-02-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_employee_encrypted_super_annuation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='encrypted_super_annuation_data',
        ),
    ]
