# Generated by Django 6.0.1 on 2026-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_employee_encrypted_super_annuation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='super_annuation_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='encrypted_super_annuation_date',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
